[package]
name = "myapp"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
myapp = "0x0"